name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.9"

    - name: pip Update
      run: |
        python -m pip install --upgrade pip
    - name: Install Pipenv
      run: |
        pip install pipenv
    - name: Install Dependencies
      run: |
        pipenv lock  # Generate a lock file if not present
        pipenv install --deploy --ignore-pipfile --python /opt/hostedtoolcache/Python/3.10.9/x64/bin/python3.10
    - name: Run Tests and Linting
      run: |
        pipenv run python main.py  # Adjust the command as needed
        
